/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package test;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Employee extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2522349042622085978L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Employee\",\"namespace\":\"test\",\"fields\":[{\"name\":\"Id\",\"type\":\"int\"},{\"name\":\"Relation\",\"type\":\"int\"},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Age\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Employee> ENCODER =
      new BinaryMessageEncoder<Employee>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Employee> DECODER =
      new BinaryMessageDecoder<Employee>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Employee> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Employee> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Employee>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Employee to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Employee from a ByteBuffer. */
  public static Employee fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int Id;
  @Deprecated public int Relation;
  @Deprecated public java.lang.CharSequence Name;
  @Deprecated public int Age;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Employee() {}

  /**
   * All-args constructor.
   * @param Id The new value for Id
   * @param Relation The new value for Relation
   * @param Name The new value for Name
   * @param Age The new value for Age
   */
  public Employee(java.lang.Integer Id, java.lang.Integer Relation, java.lang.CharSequence Name, java.lang.Integer Age) {
    this.Id = Id;
    this.Relation = Relation;
    this.Name = Name;
    this.Age = Age;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Id;
    case 1: return Relation;
    case 2: return Name;
    case 3: return Age;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Id = (java.lang.Integer)value$; break;
    case 1: Relation = (java.lang.Integer)value$; break;
    case 2: Name = (java.lang.CharSequence)value$; break;
    case 3: Age = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Id' field.
   * @return The value of the 'Id' field.
   */
  public java.lang.Integer getId() {
    return Id;
  }

  /**
   * Sets the value of the 'Id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.Id = value;
  }

  /**
   * Gets the value of the 'Relation' field.
   * @return The value of the 'Relation' field.
   */
  public java.lang.Integer getRelation() {
    return Relation;
  }

  /**
   * Sets the value of the 'Relation' field.
   * @param value the value to set.
   */
  public void setRelation(java.lang.Integer value) {
    this.Relation = value;
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.CharSequence getName() {
    return Name;
  }

  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.Name = value;
  }

  /**
   * Gets the value of the 'Age' field.
   * @return The value of the 'Age' field.
   */
  public java.lang.Integer getAge() {
    return Age;
  }

  /**
   * Sets the value of the 'Age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.Age = value;
  }

  /**
   * Creates a new Employee RecordBuilder.
   * @return A new Employee RecordBuilder
   */
  public static test.Employee.Builder newBuilder() {
    return new test.Employee.Builder();
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Employee RecordBuilder
   */
  public static test.Employee.Builder newBuilder(test.Employee.Builder other) {
    return new test.Employee.Builder(other);
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Employee instance.
   * @param other The existing instance to copy.
   * @return A new Employee RecordBuilder
   */
  public static test.Employee.Builder newBuilder(test.Employee other) {
    return new test.Employee.Builder(other);
  }

  /**
   * RecordBuilder for Employee instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Employee>
    implements org.apache.avro.data.RecordBuilder<Employee> {

    private int Id;
    private int Relation;
    private java.lang.CharSequence Name;
    private int Age;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(test.Employee.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Id)) {
        this.Id = data().deepCopy(fields()[0].schema(), other.Id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Relation)) {
        this.Relation = data().deepCopy(fields()[1].schema(), other.Relation);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Name)) {
        this.Name = data().deepCopy(fields()[2].schema(), other.Name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Age)) {
        this.Age = data().deepCopy(fields()[3].schema(), other.Age);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Employee instance
     * @param other The existing instance to copy.
     */
    private Builder(test.Employee other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Id)) {
        this.Id = data().deepCopy(fields()[0].schema(), other.Id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Relation)) {
        this.Relation = data().deepCopy(fields()[1].schema(), other.Relation);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Name)) {
        this.Name = data().deepCopy(fields()[2].schema(), other.Name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Age)) {
        this.Age = data().deepCopy(fields()[3].schema(), other.Age);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'Id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return Id;
    }

    /**
      * Sets the value of the 'Id' field.
      * @param value The value of 'Id'.
      * @return This builder.
      */
    public test.Employee.Builder setId(int value) {
      validate(fields()[0], value);
      this.Id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Id' field has been set.
      * @return True if the 'Id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Id' field.
      * @return This builder.
      */
    public test.Employee.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Relation' field.
      * @return The value.
      */
    public java.lang.Integer getRelation() {
      return Relation;
    }

    /**
      * Sets the value of the 'Relation' field.
      * @param value The value of 'Relation'.
      * @return This builder.
      */
    public test.Employee.Builder setRelation(int value) {
      validate(fields()[1], value);
      this.Relation = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Relation' field has been set.
      * @return True if the 'Relation' field has been set, false otherwise.
      */
    public boolean hasRelation() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Relation' field.
      * @return This builder.
      */
    public test.Employee.Builder clearRelation() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return Name;
    }

    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public test.Employee.Builder setName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.Name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public test.Employee.Builder clearName() {
      Name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Age' field.
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return Age;
    }

    /**
      * Sets the value of the 'Age' field.
      * @param value The value of 'Age'.
      * @return This builder.
      */
    public test.Employee.Builder setAge(int value) {
      validate(fields()[3], value);
      this.Age = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Age' field has been set.
      * @return True if the 'Age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Age' field.
      * @return This builder.
      */
    public test.Employee.Builder clearAge() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Employee build() {
      try {
        Employee record = new Employee();
        record.Id = fieldSetFlags()[0] ? this.Id : (java.lang.Integer) defaultValue(fields()[0]);
        record.Relation = fieldSetFlags()[1] ? this.Relation : (java.lang.Integer) defaultValue(fields()[1]);
        record.Name = fieldSetFlags()[2] ? this.Name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.Age = fieldSetFlags()[3] ? this.Age : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Employee>
    WRITER$ = (org.apache.avro.io.DatumWriter<Employee>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Employee>
    READER$ = (org.apache.avro.io.DatumReader<Employee>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
